apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data # Répertoire sur le nœud hôte
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-install
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/install
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-licence
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/licence
