apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-data
  labels:
    app.kubernetes.io/instance: filemaker02
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
finalizers:
  - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-install
  labels:
    app.kubernetes.io/instance: filemaker02
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
finalizers:
  - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/install
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-licence
  labels:
    app.kubernetes.io/instance: filemaker02
  annotations:
    pv.kubernetes.io/bound-by-controller: "yes"
finalizers:
  - kubernetes.io/pv-protection
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/licence
