apiVersion: v1
kind: Service
metadata:
  name: filemaker-service
spec:
  selector:
    app: filemaker  # Assurez-vous que cela correspond à l'étiquette de votre pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
    - name: odbc
      protocol: TCP
      port: 2399
      targetPort: 2399
    - name: fms
      protocol: TCP
      port: 5003
      targetPort: 5003
  type: ClusterIP  # Changez en LoadBalancer si vous avez besoin d'une IP externe
